server:
  port: 8081

spring:
  application:
    name: payment-processor
  datasource:
    url: jdbc:postgresql://localhost:5432/processor
    username: postgres
    password: postgres
  flyway:
    enabled: true

logging:
  structured:
    format:
      console: ecs

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui
